### ISSUE TITLE
V_CURRENT 

### ISSUE THREAD

**Issue by veilleenedis** [sitronlabs/MySensors-nRF24-Linky-Modue#1]
Bonjour,
Je ne voit que V_WATT, V_CURRENT n'est pas visible. Pourriez-vous svp indiquer comment avoir accès à ces données ?
;255;3;0;9;1108012 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:160
                                                                        120;2;1;0;17;160
                                                                                        0;255;3;0;9;1109455 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                                                                                                                 120;2;1;0;17;140
                                                                                                                                                                                 0;255;3;0;9;1112342 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:150
                                                         120;2;1;0;17;150
                                                                         0;255;3;0;9;1115229 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                                                                                                  120;2;1;0;17;140
                                                                                                                                                                  0;255;3;0;9;1121004 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:150
                                          120;2;1;0;17;150
                                                          0;255;3;0;9;1123890 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                                                                                   120;2;1;0;17;140
                                                                                                                                                   0;255;3;0;9;1125334 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:150
                           120;2;1;0;17;150
                                           0;255;3;0;9;1128221 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                                                                    120;2;1;0;17;140
                                                                                                                                    0;255;3;0;9;1132552 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:160
            120;2;1;0;17;160
                            0;255;3;0;9;1135438 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                                                     120;2;1;0;17;140
                                                                                                                     0;255;3;0;9;1138326 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:150
                                                                                                                                                                                              120;2;1;0;17;150
             0;255;3;0;9;1139770 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                                      120;2;1;0;17;140
                                                                                                      0;255;3;0;9;1146989 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:150
                                                                                                                                                                               120;2;1;0;17;150
                                                                                                                                                                                               0;255;3;0;9;1149876 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                                       120;2;1;0;17;140
                                                                                       0;255;3;0;9;1151319 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:150
                                                                                                                                                                120;2;1;0;17;150
                                                                                                                                                                                0;255;3;0;9;1152762 TSF:MSG:READ,120-120-0,s=2,c=1,t=17,pt=5,l=4,sg=0:140
                                                        120;2;1;0;17;140

**Comment by nschurando** [comment]
Bonjour, pourriez-vous me faire parvenir les messages de logs du module côté linky pour voir ce qu'il reçoit du compteur ?

**Comment by nschurando** [comment]
Bonjour @veilleenedis. Je vous invite à retester avec la version [v1.0.0](https://github.com/sitronlabs/MySensors-nRF24-Linky-Module/releases/tag/v1.0.0) du firmware. A votre disposition pour plus d'informations.
